# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-docstring-first
      exclude: tests
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: check-toml
    #- id: pretty-format-json
    - id: check-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ["--maxkb=1500"]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      args: [ "--profile", "black", "--filter-files" ]

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.4.1
#   hooks:
#     - id: mypy
#       exclude: "alembic|tests"
#       additional_dependencies: [ "types-requests", "types-PyYAML", "textual" ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.0
  hooks:
    # Run the linter.
 #   - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
    - id: shellcheck

# - repo: local
#   hooks:
#     - id: pytest-check
#       name: pytest-check
#       entry: tox -e py311
#       language: system
#       pass_filenames: false
#       always_run: true
